# encouragemnt.. 
import discord
from discord.ext import commands
from utils import random_color
import random

def register_encourage(bot):
    @bot.command(name='encourage')
    async def encourage(ctx):
        # prob a 100 msgs in here.
        messages = [
            "You've got this! Keep pushing forward!",
            "Remember, progress takes time. Keep studying!",
            "Believe in yourself! You're closer than you think.",
            "Every small step counts. Keep moving forward!",
            "Mistakes are proof that you are trying. Keep going!",
            "Hard work always pays off. Stay consistent!",
            "Your potential is limitless. Keep striving!",
            "Success is the result of preparation and determination.",
            "Stay positive and focused on your goals!",
            "Keep your head up; every challenge is an opportunity!",
            "You're capable of amazing things. Never doubt that!",
            "When things get tough, remember how far you've come.",
            "Keep going, one step at a time!",
            "Your future is as bright as your faith in yourself!",
            "Stay determined—great things are coming your way!",
            "Every setback is a setup for a comeback.",
            "You are stronger than you think.",
            "Don't let fear hold you back. Embrace your potential!",
            "Every day is a new opportunity to grow.",
            "Keep shining—you are a star!",
            "Stay resilient. You can overcome any obstacle.",
            "Your hard work is paying off, even if you can't see it yet.",
            "Success is a journey—enjoy the ride!",
            "Keep pushing forward, no matter what.",
            "Believe in the power of your dreams.",
            "Your efforts will lead to success, one day at a time.",
            "Embrace challenges—they help you grow.",
            "You have the strength to rise above any obstacle.",
            "Keep striving for greatness!",
            "Your determination is inspiring.",
            "Stay focused and never give up.",
            "You have what it takes to succeed!",
            "Great things are on the horizon.",
            "You are capable of overcoming any challenge.",
            "Keep moving forward with confidence.",
            "Your persistence is your power.",
            "Every day brings new opportunities.",
            "Stay strong and carry on.",
            "Your journey is unique—keep making progress.",
            "Embrace the challenge and conquer it!",
            "You are destined for success.",
            "Every effort you make brings you closer to your goal.",
            "Keep believing in yourself.",
            "Small steps lead to big achievements.",
            "Your courage is your strength.",
            "Every moment is a fresh start.",
            "Stay positive, work hard, and make it happen!",
            "Your perseverance is amazing!",
            "Keep your eyes on the prize.",
            "Never give up—success is around the corner.",
            "You are your only limit.",
            "Push yourself, because no one else is going to do it for you.",
            "Dream big, work hard, stay focused.",
            "You're doing better than you think.",
            "Keep going—you are making progress!",
            "You are capable of more than you know.",
            "Stay motivated and keep your chin up!",
            "Your passion is the fuel for your success.",
            "Keep moving forward with determination.",
            "You have the power to create change.",
            "Stay dedicated and never lose sight of your goals.",
            "Keep your spirit high and your determination higher.",
            "Every challenge is an opportunity in disguise.",
            "You're on the right track—keep it up!",
            "Keep going; you're building something amazing.",
            "Success is just around the corner.",
            "Your hard work is building a brighter future.",
            "Stay strong; you're doing great!",
            "Keep striving—every effort counts.",
            "You are the architect of your own success.",
            "Keep pushing forward, and don't look back.",
            "Every day is a chance to be better than yesterday.",
            "Your journey to success starts with one step.",
            "Keep the faith—your breakthrough is near.",
            "You are unstoppable!",
            "Keep charging ahead; your dreams await.",
            "Don't stop now; you're making progress!",
            "Keep going—success is a series of small wins.",
            "Your grit and determination are admirable.",
            "Stay focused; every step counts.",
            "Keep building your dream, one day at a time.",
            "You are more capable than you ever imagined.",
            "Never stop believing in your potential.",
            "Keep striving, and let your passion lead the way.",
            "You're making a difference, one step at a time.",
            "Keep your energy high and your goals higher.",
            "Your hard work is paving the way for success.",
            "Keep moving forward, no matter the pace.",
            "You have the strength to overcome any hurdle.",
            "Keep aiming high and reaching for the stars.",
            "Your future is bright—keep working towards it!",
            "Stay persistent, and success will follow.",
            "Every effort brings you closer to your dreams."
        ]
        message = random.choice(messages)
        embed = discord.Embed(
            title="🌟 Encouragement",
            description=message,
            color=random_color()
        )
        await ctx.send(embed=embed)
